# Generated by Django 4.2.3 on 2023-07-18 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bond',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('isin', models.CharField(max_length=12)),
                ('value', models.FloatField()),
                ('interest', models.FloatField()),
                ('interest_interval', models.IntegerField()),
                ('contract_data', models.CharField(max_length=200)),
                ('contract_expiration_data', models.CharField(max_length=200)),
                ('created', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Item',
        ),
    ]
