# Generated by Django 4.2.3 on 2023-07-19 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('base', '0003_remove_bond_contract_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='investment',
            name='bond',
        ),
        migrations.RemoveField(
            model_name='investment',
            name='user',
        ),
        migrations.AddField(
            model_name='investment',
            name='bond_isin',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='base.bond', to_field='isin'),
        ),
        migrations.AddField(
            model_name='investment',
            name='username',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, to_field='username'),
        ),
    ]
