# Generated by Django 4.2.3 on 2023-07-20 13:16

import base.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_remove_investment_bond_remove_investment_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bond',
            name='isin',
            field=models.CharField(max_length=12, null=True, unique=True, validators=[base.models._validate_isin]),
        ),
    ]
